/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Collection of all possible actions for the room core
 */
export type MatrixEvent = {
  event_id: string;
  room_id: string;
  state_key?: string | null;
  timestamp: number;
} & (
  | {
      content: MessageType;
      type: "m_room_message";
    }
  | {
      content: ReactionContent;
      type: "m_reaction";
    }
  | {
      content: RedactionContent;
      type: "m_room_redaction";
    }
  | {
      content: ReceiptType;
      type: "m_receipt";
    }
  | {
      content: RoomNameContent;
      type: "room_name";
    }
  | {
      content: RoomTopicContent;
      type: "room_topic";
    }
  | {
      content: RoomAvatarContent;
      type: "room_avatar";
    }
  | {
      content: PinnedEventsContent;
      type: "room_pinned_events";
    }
  | {
      content: CallInviteContent;
      type: "call_invite";
    }
  | {
      content: AnswerCallContent;
      type: "call_answer";
    }
  | {
      content: CallCandidatesContent;
      type: "call_candidates";
    }
  | {
      content: SelectCallAnswerContent;
      type: "call_select_answer";
    }
  | {
      content: CallNegotiationContent;
      type: "call_negotiate";
    }
  | {
      content: RejectCallContent;
      type: "call_reject";
    }
  | {
      content: HangupCallContent;
      type: "call_hangup";
    }
  | {
      content: TypingContent;
      type: "typing";
    }
  | {
      content: PresenceContent;
      type: "presence";
    }
  | {
      content: PostUserStoryContent;
      type: "user_story_post";
    }
  | {
      content: ViewUserStoryContent;
      type: "user_story_view";
    }
  | {
      content: UpdateProfileContent;
      type: "user_profile_update";
    }
);
/**
 * Events that sent actual messages that can be seen by all participants in a room.
 */
export type MessageType =
  | {
      /**
       * The body of the message
       */
      body: string;
      /**
       * The format used in formatted body
       */
      format?: string | null;
      /**
       * A formatted version of the body
       */
      formatted_body?: string | null;
      is_silent?: boolean | null;
      /**
       * Users that are mentioned in the body
       */
      mentions?: Mentions | null;
      msgtype: "text";
      new_content?: EventContent | null;
      relates_to?: RelatesTo | null;
    }
  | {
      /**
       * The body of the message
       */
      body: string;
      /**
       * The format used in formatted body
       */
      format?: string | null;
      /**
       * A formatted version of the body
       */
      formatted_body?: string | null;
      is_silent?: boolean | null;
      /**
       * Users that are mentioned in the body
       */
      mentions?: Mentions | null;
      msgtype: "notice";
      new_content?: EventContent | null;
      relates_to?: RelatesTo | null;
    }
  | {
      /**
       * a text representing the image in some way
       */
      body: string;
      /**
       * CID to the image file
       */
      file: Cid;
      /**
       * image metadata
       */
      info: ImageInfo;
      is_silent?: boolean | null;
      msgtype: "image";
      new_content?: EventContent | null;
      relates_to?: RelatesTo | null;
    }
  | {
      /**
       * a text representing the audio in same way
       */
      body: string;
      /**
       * CID to the audio file
       */
      file: Cid;
      /**
       * audio metadata
       */
      info: AudioInfo;
      is_silent?: boolean | null;
      msgtype: "audio";
      new_content?: EventContent | null;
      relates_to?: RelatesTo | null;
    }
  | {
      /**
       * textual representation of the video
       */
      body: string;
      /**
       * CID to the video
       */
      file: Cid;
      /**
       * video metadata
       */
      info: VideoInfo;
      is_silent?: boolean | null;
      msgtype: "video";
      new_content?: EventContent | null;
      relates_to?: RelatesTo | null;
    }
  | {
      /**
       * a text representing the file in some way
       */
      body: string;
      /**
       * CID to the file
       */
      file: Cid;
      /**
       * the name of the file
       */
      filename: string;
      /**
       * file metadata
       */
      info: FileInfo;
      is_silent?: boolean | null;
      msgtype: "file";
      new_content?: EventContent | null;
      relates_to?: RelatesTo | null;
    }
  | {
      /**
       * textual representation of the location
       */
      body: string;
      /**
       * a geo uri by definition of https://datatracker.ietf.org/doc/html/rfc5870
       */
      geo_uri: string;
      /**
       * location metadata
       */
      info: LocationInfo;
      is_silent?: boolean | null;
      msgtype: "location";
      new_content?: EventContent | null;
      relates_to?: RelatesTo | null;
    }
  | {
      body: string;
      info: PollCreationInfo;
      is_silent?: boolean | null;
      msgtype: "poll_start";
      new_content?: EventContent | null;
      relates_to?: RelatesTo | null;
    }
  | {
      answers: string[];
      body: string;
      is_silent?: boolean | null;
      msgtype: "poll_response";
      new_content?: EventContent | null;
      relates_to?: RelatesTo | null;
    }
  | {
      body: string;
      is_silent?: boolean | null;
      msgtype: "poll_end";
      new_content?: EventContent | null;
      relates_to?: RelatesTo | null;
    };
/**
 * Simple enum to fit the different possible contents. Unique event type string can be generated from this using pattern matching.
 *
 * # State events
 *
 * All events that in some way alter the state of a room
 *
 * - Room name - Room topic - Room avatar - Pinned events in room
 *
 * # Call Events
 *
 * All call events share the call_id, party_id and version fields call_id: A unique ID that that are used to determine which call events correspond to each other party_id: A unique ID to identify a call participant. May but not must be used for multiple calls. Must be unique across all participants. version: The version of the VoIP specs used for the message. This version is "1". A string is used for experimental versions.
 *
 * # Ephemeral events
 *
 * Ephemeral events are once-off events that do not need to be saved.
 *
 * # User events
 *
 * Events for interacting with users profiles
 */
export type EventContent =
  | {
      content: MessageType;
      type: "m_room_message";
    }
  | {
      content: ReactionContent;
      type: "m_reaction";
    }
  | {
      content: RedactionContent;
      type: "m_room_redaction";
    }
  | {
      content: ReceiptType;
      type: "m_receipt";
    }
  | {
      content: RoomNameContent;
      type: "room_name";
    }
  | {
      content: RoomTopicContent;
      type: "room_topic";
    }
  | {
      content: RoomAvatarContent;
      type: "room_avatar";
    }
  | {
      content: PinnedEventsContent;
      type: "room_pinned_events";
    }
  | {
      content: CallInviteContent;
      type: "call_invite";
    }
  | {
      content: AnswerCallContent;
      type: "call_answer";
    }
  | {
      content: CallCandidatesContent;
      type: "call_candidates";
    }
  | {
      content: SelectCallAnswerContent;
      type: "call_select_answer";
    }
  | {
      content: CallNegotiationContent;
      type: "call_negotiate";
    }
  | {
      content: RejectCallContent;
      type: "call_reject";
    }
  | {
      content: HangupCallContent;
      type: "call_hangup";
    }
  | {
      content: TypingContent;
      type: "typing";
    }
  | {
      content: PresenceContent;
      type: "presence";
    }
  | {
      content: PostUserStoryContent;
      type: "user_story_post";
    }
  | {
      content: ViewUserStoryContent;
      type: "user_story_view";
    }
  | {
      content: UpdateProfileContent;
      type: "user_profile_update";
    };
/**
 * Simple enum containing all different types of relation that events can have to other events
 */
export type RelationType = "annotation" | "replace" | "forward" | "thread" | "poll";
/**
 * Receipt events are used to indicate that all messages up to a specific event have been read by a user.
 */
export type ReceiptType =
  | {
      Public: PublicReceiptContent;
    }
  | {
      Private: PrivateReceiptContent;
    };
/**
 * Enum containg possible reasons for a hangup event
 */
export type HangupCallReason =
  | "ice_failed"
  | "ice_timeout"
  | "invite_timeout"
  | "user_hangup"
  | "user_media_failed"
  | "user_busy"
  | "unknown_error";
/**
 * Basic enum for possible presence states of a specific user
 *
 * Online: Default state when user is connected to an event stream
 *
 * Offline: The user is not connected to an event stream or is actively suppressing this information
 *
 * DnD: As 'Online' but the user doesn't want to be disturbed
 */
export type PresenceType = "online" | "offline" | "dnd";
export type PollKind = "disclosed" | "undisclosed" | "anonymous";

/**
 * Used to describe which users got mentioned in the body of a message
 */
export interface Mentions {
  user_ids: string[];
}
/**
 * Empty content as the only purpose is holding a relation to another event. Mostly used for annotation events
 */
export interface ReactionContent {
  is_silent?: boolean | null;
  new_content?: EventContent | null;
  relates_to?: RelatesTo | null;
}
/**
 * Used in some event contents to define a relation to other events
 */
export interface RelatesTo {
  event_id?: string | null;
  in_reply_to?: ReplyContent | null;
  key?: string | null;
  rel_type?: RelationType | null;
  room_id?: string | null;
}
export interface ReplyContent {
  event_id: string;
}
/**
 * Event content used to redact other events. Sender of this event must be either the same as the sender of the original event or a user with the necessary permissions. Redactions are idempotent and irreversible. They do not use the same relation fields as other events
 */
export interface RedactionContent {
  reason?: string | null;
  redacts: string;
}
/**
 * These receipts are always sent into a room and indicate to all users that the messages sent up to the indicated event were read by the user that sent this receipt event. This becomes public knowledge to all users participating in the CO.
 */
export interface PublicReceiptContent {
  "m.read": string;
  thread_id?: string | null;
}
/**
 * Private read receipts are saved in a users private CO so other users cannot infer the read status. The read map in this event only needs to contain the delta on the users receipts. This means that there is no need to contain the complete read receipt state in this event but only the changes.
 */
export interface PrivateReceiptContent {
  "m.read.private": {
    [k: string]: PrivateReceipt;
  };
}
/**
 * A read receipt for one specific room. Indicates that a user has read all messages up to the given event.
 */
export interface PrivateReceipt {
  event_id: string;
  thread_id: string;
}
export interface RoomNameContent {
  name: string;
}
export interface RoomTopicContent {
  topic: string;
}
export interface RoomAvatarContent {
  file?: Cid | null;
  info: ImageInfo;
}
export interface Cid {
  "/": string;
}
/**
 * Contains metadata of images
 */
export interface ImageInfo {
  /**
   * intended display height in px
   */
  h: number;
  /**
   * mimetype of the file
   */
  mimetype: string;
  /**
   * Size of the image file in bytes
   */
  size: number;
  /**
   * CID to an image file that is to be used as the thumbnail
   */
  thumbnail_file: Cid;
  /**
   * thumbnail metadata
   */
  thumbnail_info: ThumbnailInfo;
  /**
   * intended display width in px
   */
  w: number;
}
/**
 * Contains metadata of images used as a thumbnail
 */
export interface ThumbnailInfo {
  /**
   * intended display height in px
   */
  h: number;
  /**
   * mimetype of the file
   */
  mimetype: string;
  /**
   * Size of the image file in bytes
   */
  size: number;
  /**
   * intended display width in px
   */
  w: number;
}
export interface PinnedEventsContent {
  pinned: string[];
}
/**
 * Initial event to invite other parties to a call
 */
export interface CallInviteContent {
  call_id: string;
  /**
   * DID of the called user. Any user in room may answer if omitted
   */
  invitee?: string | null;
  /**
   * Time in ms during which invite is valid after sending this event
   */
  lifetime: number;
  /**
   * Session description object
   */
  offer: SessionDescription;
  party_id: string;
  version: string;
}
/**
 * Session description object for sdp offers and answers
 */
export interface SessionDescription {
  sdp: string;
  type: string;
}
/**
 * Event used when answering an invite event
 */
export interface AnswerCallContent {
  answer: SessionDescription;
  call_id: string;
  party_id: string;
  version: string;
}
/**
 * Event used to exchange viable ICE candidates with the other party upon answering a call
 */
export interface CallCandidatesContent {
  call_id: string;
  candidates: ICECandidate[];
  party_id: string;
  version: string;
}
/**
 * ICE candidate for WebRTC exchange protocol
 */
export interface ICECandidate {
  candidate: string;
  sdpMLineIndex: number;
  sdpMid: string;
}
/**
 * Event used to select one of possibly multiple call answers
 */
export interface SelectCallAnswerContent {
  call_id: string;
  party_id: string;
  /**
   * party id of the participant whose answer has been selected
   */
  selected_party_id: string;
  version: string;
}
/**
 * Event used to renegotiate between participants. First an offer containing a lifetime is sent. Other participants then send an answer. Offer and answer should never both be set. To ensure this they are not public to force the users to use the setters.
 */
export interface CallNegotiationContent {
  /**
   * session description object for negotioation answers
   */
  answer?: SessionDescription | null;
  call_id: string;
  /**
   * Time in ms before offer timeout
   */
  lifetime?: number | null;
  /**
   * Session description object for negotioation offers
   */
  offer?: SessionDescription | null;
  party_id: string;
  version: string;
}
/**
 * Event sent if call was rejected by a user.
 */
export interface RejectCallContent {
  call_id: string;
  party_id: string;
  version: string;
}
/**
 * Hangup event used to signal the termination of the call.
 */
export interface HangupCallContent {
  call_id: string;
  party_id: string;
  reason: HangupCallReason;
  version: string;
}
/**
 * Event used to indicate which users in the room are currently typing. Gets sent to all active users. For direct messages this information will only be shared with the other participant. Information should be updated regularly and have a timout after which no users should count as typing when no new event was sent.
 */
export interface TypingContent {
  /**
   * List of users currently typing in the room
   */
  user_ids: string[];
}
/**
 * Event content that is used to inform other users of the presence status. In contrast to typing events, the sender is important here and always corresponds to the user the information is about.
 */
export interface PresenceContent {
  /**
   * Avatar the user is currently using
   */
  avatar: Cid;
  /**
   * Whether the user is currently active
   */
  currently_active: boolean;
  /**
   * Display name of the user
   */
  display_name: string;
  /**
   * Timestampt in milliseconds when the user last performed an action
   */
  last_active: number;
  presence: PresenceType;
  /**
   * An optional arbitrary description to accompany the presence
   */
  status_msg: string;
}
export interface PostUserStoryContent {
  /**
   * Content ID for a json file containing the story data
   */
  content: Cid;
  /**
   * How long the story will be shown once opened in ms
   */
  display_time: number;
  /**
   * How long users can view the story after it was posted in ms
   */
  lifetime: number;
}
export interface ViewUserStoryContent {
  story: string;
}
export interface UpdateProfileContent {
  avatar?: Cid | null;
  display_name: string;
  status_msg: string;
}
/**
 * Contains metadata of audio files
 */
export interface AudioInfo {
  /**
   * duration of the audio clip in ms
   */
  duration: number;
  /**
   * mimetype of the audio file
   */
  mimetype: string;
  /**
   * size of the audio file in bytes
   */
  size: number;
}
/**
 * Contains metadata of video files
 */
export interface VideoInfo {
  /**
   * duration of the video clip in ms
   */
  duration: number;
  /**
   * intended display height in px
   */
  h: number;
  /**
   * mimetype of the file
   */
  mimetype: string;
  /**
   * Size of the image file in bytes
   */
  size: number;
  /**
   * CID to an image file that is to be used as the thumbnail
   */
  thumbnail_file: Cid;
  /**
   * thumbnail metadata
   */
  thumbnail_info: ThumbnailInfo;
  /**
   * intended display width in px
   */
  w: number;
}
/**
 * Contains metadata of any other filetypes
 */
export interface FileInfo {
  /**
   * mimetype of the file
   */
  mimetype: string;
  /**
   * Size of the file in bytes
   */
  size: number;
  /**
   * CID to an image file that is to be used as the thumbnail
   */
  thumbnail_file: Cid;
  /**
   * thumbnail metadata
   */
  thumbnail_info: ThumbnailInfo;
}
/**
 * Contains metadata of any location based content
 */
export interface LocationInfo {
  /**
   * CID to an image file that is to be used as the thumbnail
   */
  thumbnail_file: Cid;
  /**
   * thumbnail metadata
   */
  thumbnail_info: ThumbnailInfo;
}
/**
 * metadata for poll creation event
 */
export interface PollCreationInfo {
  answers: PollAnswer[];
  kind: PollKind;
  max_selections: number;
  question: string;
}
/**
 * One possible answer in a poll. ID should be unique across answers.
 */
export interface PollAnswer {
  answer: string;
  id: string;
}
