include: "ci/build.yml"

stages:
  - lint
  - test
  - build
  - publish

variables:
  RUST_VERSION: "1.91"
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

cache: &global_cache
  key: ${DOCKERFILE_HASH}
  paths:
    - .cargo/bin
    - .cargo/registry/index
    - .cargo/registry/cache
  policy: pull-push

# verfiy the configured in `co/build.yml` (DOCKERFILE_IMAGE) is in sync with `ci/Dockerfile`.
dockerfile:
  stage: lint
  image: ${DOCKERFILE_IMAGE}
  script:
    - echo "> test if docker image is in sync with Dockerfile (ci/build.sh)"
    - echo "${DOCKERFILE_HASH}  ci/Dockerfile" | sha256sum --check --status

# verfiy fmt/lint
lint:
  stage: lint
  image: ${DOCKERFILE_IMAGE}
  cache:
    <<: *global_cache
  script:
    - cargo +nightly-2025-12-09 fmt --check
    - cargo clippy --workspace --all-targets --all-features -- -D warnings

# verify all tests are running to success
test:
  stage: test
  image: ${DOCKERFILE_IMAGE}
  cache:
    <<: *global_cache
  variables:
    RUST_BACKTRACE: "full"
    RUST_MIN_STACK: "33554432" # 32Mib
  script:
    - cargo test
  artifacts:
    when: on_failure
    paths:
      - data

# run benchmarks
bench:
  stage: test
  image: ${DOCKERFILE_IMAGE}
  cache:
    <<: *global_cache
  script:
    - cargo bench

# generate binaries
#  note: we need to build cores before the release build to have the correct built-in core Cid's.
build:
  stage: build
  image: ${DOCKERFILE_IMAGE}
  cache:
    <<: *global_cache
  script:
    - rustc -vV
    - echo "> building cores"
    - cargo run --package co-cli --release --features bundle-wasm-cores -- core build-builtin --zst
    - echo "> building binaries"
    - cargo build --release --features bundle-wasm-cores
  artifacts:
    paths:
      - cores/Cores.toml
      - target/release/co
      - target/release/daemon
      - target-wasm/wasm32-unknown-unknown/release/*.wasm

# generate docs
rustdoc:
  stage: build
  image: ${DOCKERFILE_IMAGE}
  cache:
    <<: *global_cache
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc

# generate docs
docs:
  stage: build
  image: ${DOCKERFILE_IMAGE}
  cache:
    <<: *global_cache
  script:
    - ./ci/scripts/docs-build.sh
  artifacts:
    paths:
      - docs/book

# export pages
pages:
  stage: publish
  image: ${DOCKERFILE_IMAGE}
  dependencies:
    - build
    - rustdoc
    - docs
  cache:
    <<: *global_cache
  script:
    - mkdir -p public
    - mv target/doc public/crate
    - mv docs/book public/book
  artifacts:
    paths:
      - public
  only:
    - main
