stages:
  - test
  - build
  - publish

variables:
  RUST_VERSION: "1.76"
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

cache: &global_cache
  key: rust-${RUST_VERSION}
  paths:
    - .cargo/bin
    - .cargo/registry/index
    - .cargo/registry/cache
  policy: pull-push

test:
  stage: test
  image: docker-registry.intranet.1io.com/extern/rust:${RUST_VERSION}
  cache:
    <<: *global_cache
  script:
    - cargo test

fmt:
  stage: test
  image: docker-registry.intranet.1io.com/extern/rust:${RUST_VERSION}
  cache:
    <<: *global_cache
  script:
    - cargo fmt --check

build:
  stage: build
  image: docker-registry.intranet.1io.com/extern/rust:${RUST_VERSION}
  cache:
    <<: *global_cache
  script:
    - echo "> building binaries"
    - cargo build --release
    - echo "> building cores"
    - rustup target add wasm32-unknown-unknown
    - ./target/release/co-cli core-build-builtin
    - echo "> checking for local changes"
    - git diff-files --quiet
  artifacts:
    paths:
      - target/release/co-cli
      - target/release/daemon
      - target/wasm32-unknown-unknown/release/*.wasm

rustdoc:
  stage: build
  image: docker-registry.intranet.1io.com/extern/rust:${RUST_VERSION}
  cache:
    <<: *global_cache
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc

pages:
  stage: publish
  image: docker-registry.intranet.1io.com/extern/rust:${RUST_VERSION}
  dependencies:
    - build
    - rustdoc
  cache:
    <<: *global_cache
  script:
    - mkdir -p public
    - mv target/doc public/doc
    - mv target/release/* public/
    - mv target/wasm32-unknown-unknown/release/* public/
  artifacts:
    paths:
      - public
  only:
    - main

