include: "ci/build.yml"

stages:
  - test
  - build
  - publish

variables:
  RUST_VERSION: "1.88"
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

cache: &global_cache
  key: ${DOCKERFILE_HASH}
  paths:
    - .cargo/bin
    - .cargo/registry/index
    - .cargo/registry/cache
  policy: pull-push

# verfiy the configured in `co/build.yml` (DOCKERFILE_IMAGE) is in sync with `ci/Dockerfile`.
dockerfile:
  stage: test
  image: ${DOCKERFILE_IMAGE}
  script:
    - echo "> test if docker image is in sync with Dockerfile (ci/build.sh)"
    - echo "${DOCKERFILE_HASH}  ci/Dockerfile" | sha256sum --check --status

# verify all tests are running to success
test:
  stage: test
  image: ${DOCKERFILE_IMAGE}
  cache:
    <<: *global_cache
  script:
    - cargo test

# run benchmarks
bench:
  stage: test
  image: ${DOCKERFILE_IMAGE}
  cache:
    <<: *global_cache
  script:
    - cargo bench

# verfiy all files a re formatted correctly
fmt:
  stage: test
  image: ${DOCKERFILE_IMAGE}
  cache:
    <<: *global_cache
  script:
    - cargo +nightly fmt --check

# generate binaries
build:
  stage: build
  image: ${DOCKERFILE_IMAGE}
  cache:
    <<: *global_cache
  script:
    - echo "> building binaries"
    - cargo build --release
    - echo "> building cores"
    - ./target/release/co-cli core-build-builtin
  artifacts:
    paths:
      - target/release/co-cli
      - target/release/daemon
      - target-wasm/wasm32-unknown-unknown/release/*.wasm

# generate docs
rustdoc:
  stage: build
  image: ${DOCKERFILE_IMAGE}
  cache:
    <<: *global_cache
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc

# export pages
pages:
  stage: publish
  image: ${DOCKERFILE_IMAGE}
  dependencies:
    - build
    - rustdoc
  cache:
    <<: *global_cache
  script:
    - mkdir -p public
    - mv target/doc public/doc
    - mv target/release/* public/
    - mv target-wasm/wasm32-unknown-unknown/release/* public/
  artifacts:
    paths:
      - public
  only:
    - main
