words = [
    "autonat",
    "bitswap",
    "brandguardian",
    "cbor",
    "clippy",
    "cranelift",
    "dcutr",
    "didcomm",
    "dioxus",
    "gossipsub",
    "indexeddb",
    "jsc",
    "kad",
    "kademlia",
    "mdns",
    "thid",
    "tokio",
    "wasmer",
    "webrtc",
    "wasmi",
]
ignore_patterns = ["COkit|BRANDGUARDIAN GmbH|AGPLv3|libp2p"]
