use super::{CoreResolver, CoreResolverError};
use crate::{
	library::{core_resolver_dispatch::CoreResolverDispatch, storage_cleanup::storage_cleanup},
	reducer::change::reference_writer::{lastest_storage_reference, write_storage_references},
	CoStorage, ReducerChangeContext, CO_CORE_NAME_STORAGE,
};
use async_trait::async_trait;
use cid::Cid;
use co_primitives::{BlockLinks, BlockStorageSettings, CloneWithBlockStorageSettings};
use co_runtime::{RuntimeContext, RuntimePool};

/// Reference count state in a [`co_core_storage::Storage`] core.
#[derive(Debug, Clone)]
pub struct ReferenceCoreResolver<C> {
	next: C,
	pinning_key: Option<String>,
	block_links: BlockLinks,
}
impl<C> ReferenceCoreResolver<C> {
	pub fn new(next: C, pinning_key: Option<String>) -> Self {
		Self { next, pinning_key, block_links: Default::default() }
	}
}
#[async_trait]
impl<C> CoreResolver<CoStorage> for ReferenceCoreResolver<C>
where
	C: CoreResolver<CoStorage> + Clone + Send + Sync + 'static,
{
	#[tracing::instrument(level = tracing::Level::TRACE, skip(self, storage, runtime, state, action))]
	async fn execute(
		&self,
		storage: &CoStorage,
		runtime: &RuntimePool,
		context: &ReducerChangeContext,
		state: &Option<Cid>,
		action: &Cid,
	) -> Result<RuntimeContext, CoreResolverError> {
		// references
		//  we execute references for the previous state as the references always one state late
		//  we always want the state pinned that actually was returned by the last operation
		//  this is not possible if we pin the intermediate state generated by pin/reference/cleanup.
		let mut next_state = *state;
		if let Some(next_reference_state) = next_state {
			let mut dispatch = CoreResolverDispatch::new(
				self.next.clone(),
				runtime.clone(),
				context.clone(),
				storage.clone(),
				CO_CORE_NAME_STORAGE.to_owned(),
				next_state,
			);

			// resolve previous
			let previous_reference_state =
				lastest_storage_reference(storage, next_state.into(), &self.pinning_key).await?;

			// add
			next_state = write_storage_references(
				storage.clone_with_settings(BlockStorageSettings::new().without_networking()),
				&mut dispatch,
				self.block_links.clone(),
				self.pinning_key.clone(),
				previous_reference_state,
				next_reference_state,
				None,
			)
			.await?;

			// remove
			next_state = storage_cleanup(&mut dispatch, storage, next_state.into()).await?.0.into();
		}

		// execute
		let next = self.next.execute(&storage, runtime, context, &next_state, action).await?;

		// result
		Ok(next)
	}
}
