[cores]
co-core-co = "QmdgtQ7RqQjAetuUq5q7X38FcP2cyMQaBhvmFMhTyfY5s9"
co-core-data-series = "QmZz9tqywVH8SpdXEyiTGbFFPf9syiAu4w9UWwktGjuaJD"
co-core-file = "QmSwh3Ltdhn98qdbH45KZCyqq4kSW5v75QVu1m6uFQGGio"
co-core-keystore = "Qmf2WHd8D5T2MJukZqtnrkvGy7gZiKwVMP5j5qYtyUBiqb"
co-core-membership = "QmdtYjMtXyRTuFbjMW6QeCUCWVu2tq5AKCLvyfxc8CpjWs"
co-core-pin = "QmQ5MSNUeSVGo3knAGAJo1oMVMkbTzRq7AVX5hM2bPEfkj"
co-core-role = "QmR5rvvtg73WdgUbHXGsYEFnqBxeUH8WaUefFAFRpRy8j6"
co-core-room = "QmcBWoAA1v9U4Nm48chrFxL9UdiPUcikBFQfZ3P7jo98mr"
