[cores]
co-core-co = "Qma8Ldfms86c1yL6LfLLyBQb753zRHXWDM4Z3Vw6mGvCwi"
co-core-data-series = "QmafiiVXgqeDuYzwh4SwE7mAJdBZ9Up9TGdk1aEixWhZxn"
co-core-file = "QmYPiLSRy8aPKanWTdibnN45PUmw2jbcmo7pYjN7B1Ab85"
co-core-keystore = "QmYmWZAq8foJnZ8UsE6cXneoim8yteDEm5K4McMdfP3uBZ"
co-core-membership = "QmNvtPmV27Cs85NoL7StUDLSKXhJ4xB9ABjjDTgF1rZeKQ"
co-core-pin = "QmV37xNZ3DJWcDEXnhCDsosRCMhRrWs3aXitVME1jWRA9G"
co-core-role = "QmTA1AxcN7nekfpWMZBADiKhkXziHquHkEqC44uJrqfbEJ"
co-core-room = "QmagiuouHgY2zmBzYxbggCjanjTMeRrsThZm2xbiN4P6Rk"
