[cores]
co-core-co = "QmaYv9zJQGF5b9FiXJqvUeJAUUAisxZHAotaXdvUNmKRim"
co-core-data-series = "QmZ4oPegu3CJwMgMLGKDDydEES8ou9ddr7Zr512YZ8bVWH"
co-core-file = "QmcPe1qD78A6kJMnSn8RmzbV9z2xBJ4fS9YMpVUJnGx6xf"
co-core-keystore = "QmdNDt2tZn3JmbR7R5ggxamfonCn66SeSt8pHLYrBqNA34"
co-core-membership = "QmZnSiDQ1iLD5rq3Z81FzF5rTnKiADePQoWEUERKBmdLgP"
co-core-pin = "QmeGFQeg9hvfupm1ekhthV9YAtdhvjyiP6PDPD7W6ekSc9"
co-core-role = "QmXxY44nBRzRJ4M3oVWJnDGoNYsw1NEJWZnNmqYxpBAZ5Y"
co-core-room = "QmVQALEqcXDbYBdKBCxmk3oM3PeFtZKzD9TtTiVkMrmhoa"
