/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Tag Value
 */
export type TagValue =
  | "Null"
  | {
      Bool: boolean;
    }
  | {
      Integer: number;
    }
  | {
      Float: Double;
    }
  | {
      String: string;
    }
  | {
      Bytes: number[];
    }
  | {
      List: TagValue[];
    }
  | {
      Map: {
        [k: string]: TagValue;
      };
    }
  | {
      Link: Cid;
    };
export type Double = number;
/**
 * Tags.
 */
export type Tags = [string, TagValue][];

/**
 * eCO Messenger room core
 */
export interface Room {
  /**
   * Content ID for the room avatar
   */
  avatar?: Cid | null;
  /**
   * A short description for the room
   */
  description: string;
  /**
   * Name of the room
   */
  name: string;
  /**
   * All currently pinned messages in relevant order
   */
  pinned_messages: string[];
  tags: Tags;
}
export interface Cid {
  "/": string;
}
