// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
	non_camel_case_types,
	unused,
	non_snake_case,
	clippy::needless_return,
	clippy::redundant_closure_call,
	clippy::redundant_closure,
	clippy::useless_conversion,
	clippy::unit_arg,
	clippy::unused_unit,
	clippy::double_parens,
	clippy::let_and_return,
	clippy::too_many_arguments,
	clippy::match_single_binding,
	clippy::clone_on_copy,
	clippy::let_unit_value,
	clippy::deref_addrof,
	clippy::explicit_auto_deref,
	clippy::borrow_deref_ref,
	clippy::needless_borrow
)]

// Section: imports

use crate::library::co::*;
use crate::library::co_context::*;
use crate::library::co_error::*;
use crate::types::identity::*;
use crate::types::storage::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
	default_stream_sink_codec = SseCodec,
	default_rust_opaque = RustOpaqueMoi,
	default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -324089980;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__types__storage__BlockStorage_get_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "BlockStorage_get(dart_style=getBlock)",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that =
				<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BlockStorage>>>::sse_decode(
					&mut deserializer,
				);
			let api_cid = <crate::types::cid::Cid>::sse_decode(&mut deserializer);
			deserializer.end();
			move |context| async move {
				transform_result_sse::<_, CoError>(
					(move || async move {
						let mut api_that_guard = None;
						let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
							flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
						]);
						for i in decode_indices_ {
							match i {
								0 => api_that_guard = Some(api_that.lockable_decode_async_ref().await),
								_ => unreachable!(),
							}
						}
						let api_that_guard = api_that_guard.unwrap();
						let output_ok = crate::types::storage::BlockStorage::get(&*api_that_guard, &api_cid).await?;
						Ok(output_ok)
					})()
					.await,
				)
			}
		},
	)
}
fn wire__crate__types__storage__BlockStorage_set_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "BlockStorage_set(dart_style=setBlock)",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that =
				<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BlockStorage>>>::sse_decode(
					&mut deserializer,
				);
			let api_block = <crate::types::storage::Block>::sse_decode(&mut deserializer);
			deserializer.end();
			move |context| async move {
				transform_result_sse::<_, CoError>(
					(move || async move {
						let mut api_that_guard = None;
						let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
							flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
						]);
						for i in decode_indices_ {
							match i {
								0 => api_that_guard = Some(api_that.lockable_decode_async_ref().await),
								_ => unreachable!(),
							}
						}
						let api_that_guard = api_that_guard.unwrap();
						let output_ok = crate::types::storage::BlockStorage::set(&*api_that_guard, api_block).await?;
						Ok(output_ok)
					})()
					.await,
				)
			}
		},
	)
}
fn wire__crate__library__co_context__CoContext_create_co_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "CoContext_create_co",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that =
				<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoContext>>>::sse_decode(
					&mut deserializer,
				);
			let api_identity = <RustOpaqueMoi<
				flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoPrivateIdentity>,
			>>::sse_decode(&mut deserializer);
			let api_create = <crate::library::co_context::CreateCo>::sse_decode(&mut deserializer);
			deserializer.end();
			move |context| async move {
				transform_result_sse::<_, CoError>(
					(move || async move {
						let mut api_that_guard = None;
						let mut api_identity_guard = None;
						let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
							flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
							flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_identity, 1, false),
						]);
						for i in decode_indices_ {
							match i {
								0 => api_that_guard = Some(api_that.lockable_decode_async_ref().await),
								1 => api_identity_guard = Some(api_identity.lockable_decode_async_ref().await),
								_ => unreachable!(),
							}
						}
						let api_that_guard = api_that_guard.unwrap();
						let api_identity_guard = api_identity_guard.unwrap();
						let output_ok = crate::library::co_context::CoContext::create_co(
							&*api_that_guard,
							&*api_identity_guard,
							api_create,
						)
						.await?;
						Ok(output_ok)
					})()
					.await,
				)
			}
		},
	)
}
fn wire__crate__library__co_context__CoContext_ensure_did_key_identity_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "CoContext_ensure_did_key_identity",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that =
				<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoContext>>>::sse_decode(
					&mut deserializer,
				);
			let api_name = <String>::sse_decode(&mut deserializer);
			deserializer.end();
			move |context| async move {
				transform_result_sse::<_, CoError>(
					(move || async move {
						let mut api_that_guard = None;
						let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
							flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
						]);
						for i in decode_indices_ {
							match i {
								0 => api_that_guard = Some(api_that.lockable_decode_async_ref().await),
								_ => unreachable!(),
							}
						}
						let api_that_guard = api_that_guard.unwrap();
						let output_ok =
							crate::library::co_context::CoContext::ensure_did_key_identity(&*api_that_guard, api_name)
								.await?;
						Ok(output_ok)
					})()
					.await,
				)
			}
		},
	)
}
fn wire__crate__library__co_context__CoContext_open_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "CoContext_open",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_settings = <crate::library::co_settings::CoSettings>::sse_decode(&mut deserializer);
			deserializer.end();
			move |context| async move {
				transform_result_sse::<_, CoError>(
					(move || async move {
						let output_ok = crate::library::co_context::CoContext::open(api_settings).await?;
						Ok(output_ok)
					})()
					.await,
				)
			}
		},
	)
}
fn wire__crate__library__co_context__CoContext_open_co_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "CoContext_open_co",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that =
				<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoContext>>>::sse_decode(
					&mut deserializer,
				);
			let api_id = <String>::sse_decode(&mut deserializer);
			deserializer.end();
			move |context| async move {
				transform_result_sse::<_, CoError>(
					(move || async move {
						let mut api_that_guard = None;
						let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
							flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
						]);
						for i in decode_indices_ {
							match i {
								0 => api_that_guard = Some(api_that.lockable_decode_async_ref().await),
								_ => unreachable!(),
							}
						}
						let api_that_guard = api_that_guard.unwrap();
						let output_ok =
							crate::library::co_context::CoContext::open_co(&*api_that_guard, api_id).await?;
						Ok(output_ok)
					})()
					.await,
				)
			}
		},
	)
}
fn wire__crate__library__co_context__CoContext_resolve_private_identity_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "CoContext_resolve_private_identity",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that =
				<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoContext>>>::sse_decode(
					&mut deserializer,
				);
			let api_did = <String>::sse_decode(&mut deserializer);
			deserializer.end();
			move |context| async move {
				transform_result_sse::<_, CoError>(
					(move || async move {
						let mut api_that_guard = None;
						let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
							flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
						]);
						for i in decode_indices_ {
							match i {
								0 => api_that_guard = Some(api_that.lockable_decode_async_ref().await),
								_ => unreachable!(),
							}
						}
						let api_that_guard = api_that_guard.unwrap();
						let output_ok =
							crate::library::co_context::CoContext::resolve_private_identity(&*api_that_guard, api_did)
								.await?;
						Ok(output_ok)
					})()
					.await,
				)
			}
		},
	)
}
fn wire__crate__library__co_error__CoError_message_impl(
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "CoError_message",
			port: None,
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that =
				<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoError>>>::sse_decode(
					&mut deserializer,
				);
			deserializer.end();
			transform_result_sse::<_, ()>((move || {
				let mut api_that_guard = None;
				let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
					flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
				]);
				for i in decode_indices_ {
					match i {
						0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
						_ => unreachable!(),
					}
				}
				let api_that_guard = api_that_guard.unwrap();
				let output_ok = Result::<_, ()>::Ok(crate::library::co_error::CoError::message(&*api_that_guard))?;
				Ok(output_ok)
			})())
		},
	)
}
fn wire__crate__types__identity__CoPrivateIdentity_identity_impl(
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "CoPrivateIdentity_identity",
			port: None,
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that =
				<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoPrivateIdentity>>>::sse_decode(
					&mut deserializer,
				);
			deserializer.end();
			transform_result_sse::<_, ()>((move || {
				let mut api_that_guard = None;
				let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
					flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
				]);
				for i in decode_indices_ {
					match i {
						0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
						_ => unreachable!(),
					}
				}
				let api_that_guard = api_that_guard.unwrap();
				let output_ok =
					Result::<_, ()>::Ok(crate::types::identity::CoPrivateIdentity::identity(&*api_that_guard))?;
				Ok(output_ok)
			})())
		},
	)
}
fn wire__crate__library__co__CoSubscription_close_impl(
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "CoSubscription_close",
			port: None,
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that =
				<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoSubscription>>>::sse_decode(
					&mut deserializer,
				);
			deserializer.end();
			transform_result_sse::<_, ()>((move || {
				let mut api_that_guard = None;
				let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
					flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
				]);
				for i in decode_indices_ {
					match i {
						0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
						_ => unreachable!(),
					}
				}
				let api_that_guard = api_that_guard.unwrap();
				let output_ok = Result::<_, ()>::Ok({
					crate::library::co::CoSubscription::close(&*api_that_guard);
				})?;
				Ok(output_ok)
			})())
		},
	)
}
fn wire__crate__library__co__CoSubscription_stream_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "CoSubscription_stream",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that =
				<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoSubscription>>>::sse_decode(
					&mut deserializer,
				);
			let api_sink =
				<StreamSink<crate::library::co::CoState, flutter_rust_bridge::for_generated::SseCodec>>::sse_decode(
					&mut deserializer,
				);
			deserializer.end();
			move |context| {
				transform_result_sse::<_, ()>((move || {
					let mut api_that_guard = None;
					let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
						flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
					]);
					for i in decode_indices_ {
						match i {
							0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
							_ => unreachable!(),
						}
					}
					let api_that_guard = api_that_guard.unwrap();
					let output_ok = Result::<_, ()>::Ok({
						crate::library::co::CoSubscription::stream(&*api_that_guard, api_sink);
					})?;
					Ok(output_ok)
				})())
			}
		},
	)
}
fn wire__crate__library__co__Co_push_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "Co_push",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that = <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Co>>>::sse_decode(
				&mut deserializer,
			);
			let api_identity = <RustOpaqueMoi<
				flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoPrivateIdentity>,
			>>::sse_decode(&mut deserializer);
			let api_core = <String>::sse_decode(&mut deserializer);
			let api_action = <Vec<u8>>::sse_decode(&mut deserializer);
			deserializer.end();
			move |context| async move {
				transform_result_sse::<_, CoError>(
					(move || async move {
						let mut api_that_guard = None;
						let mut api_identity_guard = None;
						let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
							flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
							flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_identity, 1, false),
						]);
						for i in decode_indices_ {
							match i {
								0 => api_that_guard = Some(api_that.lockable_decode_async_ref().await),
								1 => api_identity_guard = Some(api_identity.lockable_decode_async_ref().await),
								_ => unreachable!(),
							}
						}
						let api_that_guard = api_that_guard.unwrap();
						let api_identity_guard = api_identity_guard.unwrap();
						let output_ok =
							crate::library::co::Co::push(&*api_that_guard, &*api_identity_guard, api_core, api_action)
								.await?;
						Ok(output_ok)
					})()
					.await,
				)
			}
		},
	)
}
fn wire__crate__library__co__Co_state_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "Co_state",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that = <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Co>>>::sse_decode(
				&mut deserializer,
			);
			deserializer.end();
			move |context| async move {
				transform_result_sse::<_, ()>(
					(move || async move {
						let mut api_that_guard = None;
						let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
							flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
						]);
						for i in decode_indices_ {
							match i {
								0 => api_that_guard = Some(api_that.lockable_decode_async_ref().await),
								_ => unreachable!(),
							}
						}
						let api_that_guard = api_that_guard.unwrap();
						let output_ok = Result::<_, ()>::Ok(crate::library::co::Co::state(&*api_that_guard).await)?;
						Ok(output_ok)
					})()
					.await,
				)
			}
		},
	)
}
fn wire__crate__library__co__Co_storage_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "Co_storage",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that = <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Co>>>::sse_decode(
				&mut deserializer,
			);
			deserializer.end();
			move |context| {
				transform_result_sse::<_, ()>((move || {
					let mut api_that_guard = None;
					let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
						flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
					]);
					for i in decode_indices_ {
						match i {
							0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
							_ => unreachable!(),
						}
					}
					let api_that_guard = api_that_guard.unwrap();
					let output_ok = Result::<_, ()>::Ok(crate::library::co::Co::storage(&*api_that_guard))?;
					Ok(output_ok)
				})())
			}
		},
	)
}
fn wire__crate__library__co__Co_subscribe_impl(
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "Co_subscribe",
			port: None,
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that = <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Co>>>::sse_decode(
				&mut deserializer,
			);
			deserializer.end();
			transform_result_sse::<_, ()>((move || {
				let mut api_that_guard = None;
				let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
					flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
				]);
				for i in decode_indices_ {
					match i {
						0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
						_ => unreachable!(),
					}
				}
				let api_that_guard = api_that_guard.unwrap();
				let output_ok = Result::<_, ()>::Ok(crate::library::co::Co::subscribe(&*api_that_guard))?;
				Ok(output_ok)
			})())
		},
	)
}
fn wire__crate__types__storage__block_new_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "block_new",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_cid = <crate::types::cid::Cid>::sse_decode(&mut deserializer);
			let api_data = <Vec<u8>>::sse_decode(&mut deserializer);
			deserializer.end();
			move |context| {
				transform_result_sse::<_, CoError>((move || {
					let output_ok = crate::types::storage::Block::new(api_cid, api_data)?;
					Ok(output_ok)
				})())
			}
		},
	)
}
fn wire__crate__types__storage__block_new_data_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "block_new_data",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_codec = <u64>::sse_decode(&mut deserializer);
			let api_data = <Vec<u8>>::sse_decode(&mut deserializer);
			deserializer.end();
			move |context| {
				transform_result_sse::<_, ()>((move || {
					let output_ok = Result::<_, ()>::Ok(crate::types::storage::Block::new_data(api_codec, api_data))?;
					Ok(output_ok)
				})())
			}
		},
	)
}
fn wire__crate__types__storage__block_new_unchecked_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "block_new_unchecked",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_cid = <crate::types::cid::Cid>::sse_decode(&mut deserializer);
			let api_data = <Vec<u8>>::sse_decode(&mut deserializer);
			deserializer.end();
			move |context| {
				transform_result_sse::<_, ()>((move || {
					let output_ok =
						Result::<_, ()>::Ok(crate::types::storage::Block::new_unchecked(api_cid, api_data))?;
					Ok(output_ok)
				})())
			}
		},
	)
}
fn wire__crate__types__cid__cid_codec_impl(
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "cid_codec",
			port: None,
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that = <crate::types::cid::Cid>::sse_decode(&mut deserializer);
			deserializer.end();
			transform_result_sse::<_, CoError>((move || {
				let output_ok = crate::types::cid::Cid::codec(&api_that)?;
				Ok(output_ok)
			})())
		},
	)
}
fn wire__crate__types__cid__cid_from_string_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "cid_from_string",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_string = <String>::sse_decode(&mut deserializer);
			deserializer.end();
			move |context| {
				transform_result_sse::<_, CoError>((move || {
					let output_ok = crate::types::cid::Cid::from_string(api_string)?;
					Ok(output_ok)
				})())
			}
		},
	)
}
fn wire__crate__types__cid__cid_to_string_impl(
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "cid_to_string",
			port: None,
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that = <crate::types::cid::Cid>::sse_decode(&mut deserializer);
			deserializer.end();
			transform_result_sse::<_, CoError>((move || {
				let output_ok = crate::types::cid::Cid::to_string(&api_that)?;
				Ok(output_ok)
			})())
		},
	)
}
fn wire__crate__types__cid__cid_version_impl(
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "cid_version",
			port: None,
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that = <crate::types::cid::Cid>::sse_decode(&mut deserializer);
			deserializer.end();
			transform_result_sse::<_, CoError>((move || {
				let output_ok = crate::types::cid::Cid::version(&api_that)?;
				Ok(output_ok)
			})())
		},
	)
}
fn wire__crate__types__level__co_log_level_default_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "co_log_level_default",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			deserializer.end();
			move |context| {
				transform_result_sse::<_, ()>((move || {
					let output_ok = Result::<_, ()>::Ok(crate::types::level::CoLogLevel::default())?;
					Ok(output_ok)
				})())
			}
		},
	)
}
fn wire__crate__types__network_settings__co_network_settings_default_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "co_network_settings_default",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			deserializer.end();
			move |context| {
				transform_result_sse::<_, ()>((move || {
					let output_ok = Result::<_, ()>::Ok(crate::types::network_settings::CoNetworkSettings::default())?;
					Ok(output_ok)
				})())
			}
		},
	)
}
fn wire__crate__library__co_settings__co_settings_default_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "co_settings_default",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			deserializer.end();
			move |context| {
				transform_result_sse::<_, ()>((move || {
					let output_ok = Result::<_, ()>::Ok(crate::library::co_settings::CoSettings::default())?;
					Ok(output_ok)
				})())
			}
		},
	)
}

// Section: related_funcs

flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
	flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BlockStorage>
);
flutter_rust_bridge::frb_generated_moi_arc_impl_value!(flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Co>);
flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
	flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoContext>
);
flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
	flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoError>
);
flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
	flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoPrivateIdentity>
);
flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
	flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoSubscription>
);

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <String>::sse_decode(deserializer);
		return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
	}
}

impl SseDecode for BlockStorage {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner =
			<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BlockStorage>>>::sse_decode(
				deserializer,
			);
		return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
	}
}

impl SseDecode for Co {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner =
			<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Co>>>::sse_decode(deserializer);
		return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
	}
}

impl SseDecode for CoContext {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoContext>>>::sse_decode(
			deserializer,
		);
		return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
	}
}

impl SseDecode for CoError {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner =
			<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoError>>>::sse_decode(deserializer);
		return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
	}
}

impl SseDecode for CoPrivateIdentity {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner =
			<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoPrivateIdentity>>>::sse_decode(
				deserializer,
			);
		return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
	}
}

impl SseDecode for CoSubscription {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner =
			<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoSubscription>>>::sse_decode(
				deserializer,
			);
		return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
	}
}

impl SseDecode for std::collections::HashMap<String, crate::library::co_context::CreateCore> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <Vec<(String, crate::library::co_context::CreateCore)>>::sse_decode(deserializer);
		return inner.into_iter().collect();
	}
}

impl SseDecode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BlockStorage>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <usize>::sse_decode(deserializer);
		return decode_rust_opaque_moi(inner);
	}
}

impl SseDecode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Co>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <usize>::sse_decode(deserializer);
		return decode_rust_opaque_moi(inner);
	}
}

impl SseDecode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoContext>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <usize>::sse_decode(deserializer);
		return decode_rust_opaque_moi(inner);
	}
}

impl SseDecode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoError>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <usize>::sse_decode(deserializer);
		return decode_rust_opaque_moi(inner);
	}
}

impl SseDecode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoPrivateIdentity>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <usize>::sse_decode(deserializer);
		return decode_rust_opaque_moi(inner);
	}
}

impl SseDecode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoSubscription>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <usize>::sse_decode(deserializer);
		return decode_rust_opaque_moi(inner);
	}
}

impl SseDecode for StreamSink<crate::library::co::CoState, flutter_rust_bridge::for_generated::SseCodec> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <String>::sse_decode(deserializer);
		return StreamSink::deserialize(inner);
	}
}

impl SseDecode for String {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <Vec<u8>>::sse_decode(deserializer);
		return String::from_utf8(inner).unwrap();
	}
}

impl SseDecode for crate::types::storage::Block {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut var_cid = <crate::types::cid::Cid>::sse_decode(deserializer);
		let mut var_data = <Vec<u8>>::sse_decode(deserializer);
		return crate::types::storage::Block { cid: var_cid, data: var_data };
	}
}

impl SseDecode for bool {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		deserializer.cursor.read_u8().unwrap() != 0
	}
}

impl SseDecode for crate::types::cid::Cid {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut var_bytes = <Vec<u8>>::sse_decode(deserializer);
		return crate::types::cid::Cid { bytes: var_bytes };
	}
}

impl SseDecode for crate::types::level::CoLogLevel {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <i32>::sse_decode(deserializer);
		return match inner {
			0 => crate::types::level::CoLogLevel::Error,
			1 => crate::types::level::CoLogLevel::Warn,
			2 => crate::types::level::CoLogLevel::Info,
			3 => crate::types::level::CoLogLevel::Debug,
			4 => crate::types::level::CoLogLevel::Trace,
			_ => unreachable!("Invalid variant for CoLogLevel: {}", inner),
		};
	}
}

impl SseDecode for crate::types::network_settings::CoNetworkSettings {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut var_forceNewPeerId = <bool>::sse_decode(deserializer);
		let mut var_listen = <String>::sse_decode(deserializer);
		let mut var_bootstrap = <Vec<String>>::sse_decode(deserializer);
		let mut var_externalAddresses = <Vec<String>>::sse_decode(deserializer);
		let mut var_keepAliveMs = <u64>::sse_decode(deserializer);
		let mut var_peersThreshold = <Option<u32>>::sse_decode(deserializer);
		let mut var_relay = <bool>::sse_decode(deserializer);
		let mut var_nat = <bool>::sse_decode(deserializer);
		let mut var_mdns = <bool>::sse_decode(deserializer);
		return crate::types::network_settings::CoNetworkSettings {
			force_new_peer_id: var_forceNewPeerId,
			listen: var_listen,
			bootstrap: var_bootstrap,
			external_addresses: var_externalAddresses,
			keep_alive_ms: var_keepAliveMs,
			peers_threshold: var_peersThreshold,
			relay: var_relay,
			nat: var_nat,
			mdns: var_mdns,
		};
	}
}

impl SseDecode for crate::library::co_settings::CoSettings {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut var_identifier = <String>::sse_decode(deserializer);
		let mut var_path = <Option<String>>::sse_decode(deserializer);
		let mut var_networkSettings =
			<Option<crate::types::network_settings::CoNetworkSettings>>::sse_decode(deserializer);
		let mut var_network = <Option<bool>>::sse_decode(deserializer);
		let mut var_noKeychain = <Option<bool>>::sse_decode(deserializer);
		let mut var_noLog = <Option<bool>>::sse_decode(deserializer);
		let mut var_logLevel = <Option<crate::types::level::CoLogLevel>>::sse_decode(deserializer);
		let mut var_noDefaultFeatures = <Option<bool>>::sse_decode(deserializer);
		let mut var_feature = <Option<Vec<String>>>::sse_decode(deserializer);
		return crate::library::co_settings::CoSettings {
			identifier: var_identifier,
			path: var_path,
			network_settings: var_networkSettings,
			network: var_network,
			no_keychain: var_noKeychain,
			no_log: var_noLog,
			log_level: var_logLevel,
			no_default_features: var_noDefaultFeatures,
			feature: var_feature,
		};
	}
}

impl SseDecode for crate::library::co::CoState {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut var_state = <Option<crate::types::cid::Cid>>::sse_decode(deserializer);
		let mut var_heads = <Vec<crate::types::cid::Cid>>::sse_decode(deserializer);
		return crate::library::co::CoState { state: var_state, heads: var_heads };
	}
}

impl SseDecode for crate::library::co_context::CreateCo {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut var_id = <String>::sse_decode(deserializer);
		let mut var_name = <Option<String>>::sse_decode(deserializer);
		let mut var_public = <bool>::sse_decode(deserializer);
		let mut var_cores =
			<std::collections::HashMap<String, crate::library::co_context::CreateCore>>::sse_decode(deserializer);
		return crate::library::co_context::CreateCo {
			id: var_id,
			name: var_name,
			public: var_public,
			cores: var_cores,
		};
	}
}

impl SseDecode for crate::library::co_context::CreateCore {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut var_coreType = <String>::sse_decode(deserializer);
		let mut var_coreReference = <Option<crate::types::cid::Cid>>::sse_decode(deserializer);
		let mut var_coreBytes = <Option<Vec<u8>>>::sse_decode(deserializer);
		return crate::library::co_context::CreateCore {
			core_type: var_coreType,
			core_reference: var_coreReference,
			core_bytes: var_coreBytes,
		};
	}
}

impl SseDecode for i32 {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		deserializer.cursor.read_i32::<NativeEndian>().unwrap()
	}
}

impl SseDecode for Vec<String> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut len_ = <i32>::sse_decode(deserializer);
		let mut ans_ = vec![];
		for idx_ in 0..len_ {
			ans_.push(<String>::sse_decode(deserializer));
		}
		return ans_;
	}
}

impl SseDecode for Vec<crate::types::cid::Cid> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut len_ = <i32>::sse_decode(deserializer);
		let mut ans_ = vec![];
		for idx_ in 0..len_ {
			ans_.push(<crate::types::cid::Cid>::sse_decode(deserializer));
		}
		return ans_;
	}
}

impl SseDecode for Vec<u8> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut len_ = <i32>::sse_decode(deserializer);
		let mut ans_ = vec![];
		for idx_ in 0..len_ {
			ans_.push(<u8>::sse_decode(deserializer));
		}
		return ans_;
	}
}

impl SseDecode for Vec<(String, crate::library::co_context::CreateCore)> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut len_ = <i32>::sse_decode(deserializer);
		let mut ans_ = vec![];
		for idx_ in 0..len_ {
			ans_.push(<(String, crate::library::co_context::CreateCore)>::sse_decode(deserializer));
		}
		return ans_;
	}
}

impl SseDecode for Option<String> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		if (<bool>::sse_decode(deserializer)) {
			return Some(<String>::sse_decode(deserializer));
		} else {
			return None;
		}
	}
}

impl SseDecode for Option<bool> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		if (<bool>::sse_decode(deserializer)) {
			return Some(<bool>::sse_decode(deserializer));
		} else {
			return None;
		}
	}
}

impl SseDecode for Option<crate::types::cid::Cid> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		if (<bool>::sse_decode(deserializer)) {
			return Some(<crate::types::cid::Cid>::sse_decode(deserializer));
		} else {
			return None;
		}
	}
}

impl SseDecode for Option<crate::types::level::CoLogLevel> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		if (<bool>::sse_decode(deserializer)) {
			return Some(<crate::types::level::CoLogLevel>::sse_decode(deserializer));
		} else {
			return None;
		}
	}
}

impl SseDecode for Option<crate::types::network_settings::CoNetworkSettings> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		if (<bool>::sse_decode(deserializer)) {
			return Some(<crate::types::network_settings::CoNetworkSettings>::sse_decode(deserializer));
		} else {
			return None;
		}
	}
}

impl SseDecode for Option<u32> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		if (<bool>::sse_decode(deserializer)) {
			return Some(<u32>::sse_decode(deserializer));
		} else {
			return None;
		}
	}
}

impl SseDecode for Option<Vec<String>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		if (<bool>::sse_decode(deserializer)) {
			return Some(<Vec<String>>::sse_decode(deserializer));
		} else {
			return None;
		}
	}
}

impl SseDecode for Option<Vec<u8>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		if (<bool>::sse_decode(deserializer)) {
			return Some(<Vec<u8>>::sse_decode(deserializer));
		} else {
			return None;
		}
	}
}

impl SseDecode for (String, crate::library::co_context::CreateCore) {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut var_field0 = <String>::sse_decode(deserializer);
		let mut var_field1 = <crate::library::co_context::CreateCore>::sse_decode(deserializer);
		return (var_field0, var_field1);
	}
}

impl SseDecode for u32 {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		deserializer.cursor.read_u32::<NativeEndian>().unwrap()
	}
}

impl SseDecode for u64 {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		deserializer.cursor.read_u64::<NativeEndian>().unwrap()
	}
}

impl SseDecode for u8 {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		deserializer.cursor.read_u8().unwrap()
	}
}

impl SseDecode for () {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
	}
}

fn pde_ffi_dispatcher_primary_impl(
	func_id: i32,
	port: flutter_rust_bridge::for_generated::MessagePort,
	ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len: i32,
	data_len: i32,
) {
	// Codec=Pde (Serialization + dispatch), see doc to use other codecs
	match func_id {
		1 => wire__crate__types__storage__BlockStorage_get_impl(port, ptr, rust_vec_len, data_len),
		2 => wire__crate__types__storage__BlockStorage_set_impl(port, ptr, rust_vec_len, data_len),
		3 => wire__crate__library__co_context__CoContext_create_co_impl(port, ptr, rust_vec_len, data_len),
		4 => {
			wire__crate__library__co_context__CoContext_ensure_did_key_identity_impl(port, ptr, rust_vec_len, data_len)
		},
		5 => wire__crate__library__co_context__CoContext_open_impl(port, ptr, rust_vec_len, data_len),
		6 => wire__crate__library__co_context__CoContext_open_co_impl(port, ptr, rust_vec_len, data_len),
		7 => {
			wire__crate__library__co_context__CoContext_resolve_private_identity_impl(port, ptr, rust_vec_len, data_len)
		},
		11 => wire__crate__library__co__CoSubscription_stream_impl(port, ptr, rust_vec_len, data_len),
		12 => wire__crate__library__co__Co_push_impl(port, ptr, rust_vec_len, data_len),
		13 => wire__crate__library__co__Co_state_impl(port, ptr, rust_vec_len, data_len),
		14 => wire__crate__library__co__Co_storage_impl(port, ptr, rust_vec_len, data_len),
		16 => wire__crate__types__storage__block_new_impl(port, ptr, rust_vec_len, data_len),
		17 => wire__crate__types__storage__block_new_data_impl(port, ptr, rust_vec_len, data_len),
		18 => wire__crate__types__storage__block_new_unchecked_impl(port, ptr, rust_vec_len, data_len),
		20 => wire__crate__types__cid__cid_from_string_impl(port, ptr, rust_vec_len, data_len),
		23 => wire__crate__types__level__co_log_level_default_impl(port, ptr, rust_vec_len, data_len),
		24 => wire__crate__types__network_settings__co_network_settings_default_impl(port, ptr, rust_vec_len, data_len),
		25 => wire__crate__library__co_settings__co_settings_default_impl(port, ptr, rust_vec_len, data_len),
		_ => unreachable!(),
	}
}

fn pde_ffi_dispatcher_sync_impl(
	func_id: i32,
	ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len: i32,
	data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
	// Codec=Pde (Serialization + dispatch), see doc to use other codecs
	match func_id {
		8 => wire__crate__library__co_error__CoError_message_impl(ptr, rust_vec_len, data_len),
		9 => wire__crate__types__identity__CoPrivateIdentity_identity_impl(ptr, rust_vec_len, data_len),
		10 => wire__crate__library__co__CoSubscription_close_impl(ptr, rust_vec_len, data_len),
		15 => wire__crate__library__co__Co_subscribe_impl(ptr, rust_vec_len, data_len),
		19 => wire__crate__types__cid__cid_codec_impl(ptr, rust_vec_len, data_len),
		21 => wire__crate__types__cid__cid_to_string_impl(ptr, rust_vec_len, data_len),
		22 => wire__crate__types__cid__cid_version_impl(ptr, rust_vec_len, data_len),
		_ => unreachable!(),
	}
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<BlockStorage> {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0).into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<BlockStorage> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<BlockStorage>> for BlockStorage {
	fn into_into_dart(self) -> FrbWrapper<BlockStorage> {
		self.into()
	}
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<Co> {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0).into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<Co> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<Co>> for Co {
	fn into_into_dart(self) -> FrbWrapper<Co> {
		self.into()
	}
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<CoContext> {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0).into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<CoContext> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<CoContext>> for CoContext {
	fn into_into_dart(self) -> FrbWrapper<CoContext> {
		self.into()
	}
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<CoError> {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0).into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<CoError> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<CoError>> for CoError {
	fn into_into_dart(self) -> FrbWrapper<CoError> {
		self.into()
	}
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<CoPrivateIdentity> {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0).into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<CoPrivateIdentity> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<CoPrivateIdentity>> for CoPrivateIdentity {
	fn into_into_dart(self) -> FrbWrapper<CoPrivateIdentity> {
		self.into()
	}
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<CoSubscription> {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0).into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<CoSubscription> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<CoSubscription>> for CoSubscription {
	fn into_into_dart(self) -> FrbWrapper<CoSubscription> {
		self.into()
	}
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::storage::Block {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		[self.cid.into_into_dart().into_dart(), self.data.into_into_dart().into_dart()].into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::storage::Block {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::storage::Block> for crate::types::storage::Block {
	fn into_into_dart(self) -> crate::types::storage::Block {
		self
	}
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::cid::Cid {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		[self.bytes.into_into_dart().into_dart()].into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::cid::Cid {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::cid::Cid> for crate::types::cid::Cid {
	fn into_into_dart(self) -> crate::types::cid::Cid {
		self
	}
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::level::CoLogLevel {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		match self {
			Self::Error => 0.into_dart(),
			Self::Warn => 1.into_dart(),
			Self::Info => 2.into_dart(),
			Self::Debug => 3.into_dart(),
			Self::Trace => 4.into_dart(),
			_ => unreachable!(),
		}
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::level::CoLogLevel {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::level::CoLogLevel> for crate::types::level::CoLogLevel {
	fn into_into_dart(self) -> crate::types::level::CoLogLevel {
		self
	}
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::network_settings::CoNetworkSettings {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		[
			self.force_new_peer_id.into_into_dart().into_dart(),
			self.listen.into_into_dart().into_dart(),
			self.bootstrap.into_into_dart().into_dart(),
			self.external_addresses.into_into_dart().into_dart(),
			self.keep_alive_ms.into_into_dart().into_dart(),
			self.peers_threshold.into_into_dart().into_dart(),
			self.relay.into_into_dart().into_dart(),
			self.nat.into_into_dart().into_dart(),
			self.mdns.into_into_dart().into_dart(),
		]
		.into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::network_settings::CoNetworkSettings {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::network_settings::CoNetworkSettings>
	for crate::types::network_settings::CoNetworkSettings
{
	fn into_into_dart(self) -> crate::types::network_settings::CoNetworkSettings {
		self
	}
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::library::co_settings::CoSettings {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		[
			self.identifier.into_into_dart().into_dart(),
			self.path.into_into_dart().into_dart(),
			self.network_settings.into_into_dart().into_dart(),
			self.network.into_into_dart().into_dart(),
			self.no_keychain.into_into_dart().into_dart(),
			self.no_log.into_into_dart().into_dart(),
			self.log_level.into_into_dart().into_dart(),
			self.no_default_features.into_into_dart().into_dart(),
			self.feature.into_into_dart().into_dart(),
		]
		.into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::library::co_settings::CoSettings {}
impl flutter_rust_bridge::IntoIntoDart<crate::library::co_settings::CoSettings>
	for crate::library::co_settings::CoSettings
{
	fn into_into_dart(self) -> crate::library::co_settings::CoSettings {
		self
	}
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::library::co::CoState {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		[self.state.into_into_dart().into_dart(), self.heads.into_into_dart().into_dart()].into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::library::co::CoState {}
impl flutter_rust_bridge::IntoIntoDart<crate::library::co::CoState> for crate::library::co::CoState {
	fn into_into_dart(self) -> crate::library::co::CoState {
		self
	}
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::library::co_context::CreateCo {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		[
			self.id.into_into_dart().into_dart(),
			self.name.into_into_dart().into_dart(),
			self.public.into_into_dart().into_dart(),
			self.cores.into_into_dart().into_dart(),
		]
		.into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::library::co_context::CreateCo {}
impl flutter_rust_bridge::IntoIntoDart<crate::library::co_context::CreateCo> for crate::library::co_context::CreateCo {
	fn into_into_dart(self) -> crate::library::co_context::CreateCo {
		self
	}
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::library::co_context::CreateCore {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		[
			self.core_type.into_into_dart().into_dart(),
			self.core_reference.into_into_dart().into_dart(),
			self.core_bytes.into_into_dart().into_dart(),
		]
		.into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::library::co_context::CreateCore {}
impl flutter_rust_bridge::IntoIntoDart<crate::library::co_context::CreateCore>
	for crate::library::co_context::CreateCore
{
	fn into_into_dart(self) -> crate::library::co_context::CreateCore {
		self
	}
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<String>::sse_encode(format!("{:?}", self), serializer);
	}
}

impl SseEncode for BlockStorage {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BlockStorage>>>::sse_encode(
			flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self),
			serializer,
		);
	}
}

impl SseEncode for Co {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Co>>>::sse_encode(
			flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self),
			serializer,
		);
	}
}

impl SseEncode for CoContext {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoContext>>>::sse_encode(
			flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self),
			serializer,
		);
	}
}

impl SseEncode for CoError {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoError>>>::sse_encode(
			flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self),
			serializer,
		);
	}
}

impl SseEncode for CoPrivateIdentity {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoPrivateIdentity>>>::sse_encode(
			flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self),
			serializer,
		);
	}
}

impl SseEncode for CoSubscription {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoSubscription>>>::sse_encode(
			flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self),
			serializer,
		);
	}
}

impl SseEncode for std::collections::HashMap<String, crate::library::co_context::CreateCore> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<Vec<(String, crate::library::co_context::CreateCore)>>::sse_encode(self.into_iter().collect(), serializer);
	}
}

impl SseEncode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BlockStorage>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		let (ptr, size) = self.sse_encode_raw();
		<usize>::sse_encode(ptr, serializer);
		<i32>::sse_encode(size, serializer);
	}
}

impl SseEncode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Co>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		let (ptr, size) = self.sse_encode_raw();
		<usize>::sse_encode(ptr, serializer);
		<i32>::sse_encode(size, serializer);
	}
}

impl SseEncode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoContext>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		let (ptr, size) = self.sse_encode_raw();
		<usize>::sse_encode(ptr, serializer);
		<i32>::sse_encode(size, serializer);
	}
}

impl SseEncode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoError>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		let (ptr, size) = self.sse_encode_raw();
		<usize>::sse_encode(ptr, serializer);
		<i32>::sse_encode(size, serializer);
	}
}

impl SseEncode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoPrivateIdentity>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		let (ptr, size) = self.sse_encode_raw();
		<usize>::sse_encode(ptr, serializer);
		<i32>::sse_encode(size, serializer);
	}
}

impl SseEncode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoSubscription>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		let (ptr, size) = self.sse_encode_raw();
		<usize>::sse_encode(ptr, serializer);
		<i32>::sse_encode(size, serializer);
	}
}

impl SseEncode for StreamSink<crate::library::co::CoState, flutter_rust_bridge::for_generated::SseCodec> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		unimplemented!("")
	}
}

impl SseEncode for String {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<Vec<u8>>::sse_encode(self.into_bytes(), serializer);
	}
}

impl SseEncode for crate::types::storage::Block {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<crate::types::cid::Cid>::sse_encode(self.cid, serializer);
		<Vec<u8>>::sse_encode(self.data, serializer);
	}
}

impl SseEncode for bool {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		serializer.cursor.write_u8(self as _).unwrap();
	}
}

impl SseEncode for crate::types::cid::Cid {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<Vec<u8>>::sse_encode(self.bytes, serializer);
	}
}

impl SseEncode for crate::types::level::CoLogLevel {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<i32>::sse_encode(
			match self {
				crate::types::level::CoLogLevel::Error => 0,
				crate::types::level::CoLogLevel::Warn => 1,
				crate::types::level::CoLogLevel::Info => 2,
				crate::types::level::CoLogLevel::Debug => 3,
				crate::types::level::CoLogLevel::Trace => 4,
				_ => {
					unimplemented!("");
				},
			},
			serializer,
		);
	}
}

impl SseEncode for crate::types::network_settings::CoNetworkSettings {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<bool>::sse_encode(self.force_new_peer_id, serializer);
		<String>::sse_encode(self.listen, serializer);
		<Vec<String>>::sse_encode(self.bootstrap, serializer);
		<Vec<String>>::sse_encode(self.external_addresses, serializer);
		<u64>::sse_encode(self.keep_alive_ms, serializer);
		<Option<u32>>::sse_encode(self.peers_threshold, serializer);
		<bool>::sse_encode(self.relay, serializer);
		<bool>::sse_encode(self.nat, serializer);
		<bool>::sse_encode(self.mdns, serializer);
	}
}

impl SseEncode for crate::library::co_settings::CoSettings {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<String>::sse_encode(self.identifier, serializer);
		<Option<String>>::sse_encode(self.path, serializer);
		<Option<crate::types::network_settings::CoNetworkSettings>>::sse_encode(self.network_settings, serializer);
		<Option<bool>>::sse_encode(self.network, serializer);
		<Option<bool>>::sse_encode(self.no_keychain, serializer);
		<Option<bool>>::sse_encode(self.no_log, serializer);
		<Option<crate::types::level::CoLogLevel>>::sse_encode(self.log_level, serializer);
		<Option<bool>>::sse_encode(self.no_default_features, serializer);
		<Option<Vec<String>>>::sse_encode(self.feature, serializer);
	}
}

impl SseEncode for crate::library::co::CoState {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<Option<crate::types::cid::Cid>>::sse_encode(self.state, serializer);
		<Vec<crate::types::cid::Cid>>::sse_encode(self.heads, serializer);
	}
}

impl SseEncode for crate::library::co_context::CreateCo {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<String>::sse_encode(self.id, serializer);
		<Option<String>>::sse_encode(self.name, serializer);
		<bool>::sse_encode(self.public, serializer);
		<std::collections::HashMap<String, crate::library::co_context::CreateCore>>::sse_encode(self.cores, serializer);
	}
}

impl SseEncode for crate::library::co_context::CreateCore {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<String>::sse_encode(self.core_type, serializer);
		<Option<crate::types::cid::Cid>>::sse_encode(self.core_reference, serializer);
		<Option<Vec<u8>>>::sse_encode(self.core_bytes, serializer);
	}
}

impl SseEncode for i32 {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
	}
}

impl SseEncode for Vec<String> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<i32>::sse_encode(self.len() as _, serializer);
		for item in self {
			<String>::sse_encode(item, serializer);
		}
	}
}

impl SseEncode for Vec<crate::types::cid::Cid> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<i32>::sse_encode(self.len() as _, serializer);
		for item in self {
			<crate::types::cid::Cid>::sse_encode(item, serializer);
		}
	}
}

impl SseEncode for Vec<u8> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<i32>::sse_encode(self.len() as _, serializer);
		for item in self {
			<u8>::sse_encode(item, serializer);
		}
	}
}

impl SseEncode for Vec<(String, crate::library::co_context::CreateCore)> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<i32>::sse_encode(self.len() as _, serializer);
		for item in self {
			<(String, crate::library::co_context::CreateCore)>::sse_encode(item, serializer);
		}
	}
}

impl SseEncode for Option<String> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<bool>::sse_encode(self.is_some(), serializer);
		if let Some(value) = self {
			<String>::sse_encode(value, serializer);
		}
	}
}

impl SseEncode for Option<bool> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<bool>::sse_encode(self.is_some(), serializer);
		if let Some(value) = self {
			<bool>::sse_encode(value, serializer);
		}
	}
}

impl SseEncode for Option<crate::types::cid::Cid> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<bool>::sse_encode(self.is_some(), serializer);
		if let Some(value) = self {
			<crate::types::cid::Cid>::sse_encode(value, serializer);
		}
	}
}

impl SseEncode for Option<crate::types::level::CoLogLevel> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<bool>::sse_encode(self.is_some(), serializer);
		if let Some(value) = self {
			<crate::types::level::CoLogLevel>::sse_encode(value, serializer);
		}
	}
}

impl SseEncode for Option<crate::types::network_settings::CoNetworkSettings> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<bool>::sse_encode(self.is_some(), serializer);
		if let Some(value) = self {
			<crate::types::network_settings::CoNetworkSettings>::sse_encode(value, serializer);
		}
	}
}

impl SseEncode for Option<u32> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<bool>::sse_encode(self.is_some(), serializer);
		if let Some(value) = self {
			<u32>::sse_encode(value, serializer);
		}
	}
}

impl SseEncode for Option<Vec<String>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<bool>::sse_encode(self.is_some(), serializer);
		if let Some(value) = self {
			<Vec<String>>::sse_encode(value, serializer);
		}
	}
}

impl SseEncode for Option<Vec<u8>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<bool>::sse_encode(self.is_some(), serializer);
		if let Some(value) = self {
			<Vec<u8>>::sse_encode(value, serializer);
		}
	}
}

impl SseEncode for (String, crate::library::co_context::CreateCore) {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<String>::sse_encode(self.0, serializer);
		<crate::library::co_context::CreateCore>::sse_encode(self.1, serializer);
	}
}

impl SseEncode for u32 {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
	}
}

impl SseEncode for u64 {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
	}
}

impl SseEncode for u8 {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		serializer.cursor.write_u8(self).unwrap();
	}
}

impl SseEncode for () {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		serializer.cursor.write_u64::<NativeEndian>(self as _).unwrap();
	}
}

#[cfg(not(target_family = "wasm"))]
mod io {
	// This file is automatically generated, so please do not edit it.
	// @generated by `flutter_rust_bridge`@ 2.11.1.

	// Section: imports

	use super::*;
	use crate::library::co::*;
	use crate::library::co_context::*;
	use crate::library::co_error::*;
	use crate::types::identity::*;
	use crate::types::storage::*;
	use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
	use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
	use flutter_rust_bridge::{Handler, IntoIntoDart};

	// Section: boilerplate

	flutter_rust_bridge::frb_generated_boilerplate_io!();

	#[unsafe(no_mangle)]
	pub extern "C" fn frbgen_co_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlockStorage(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BlockStorage>>::increment_strong_count(
			ptr as _,
		);
	}

	#[unsafe(no_mangle)]
	pub extern "C" fn frbgen_co_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlockStorage(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BlockStorage>>::decrement_strong_count(
			ptr as _,
		);
	}

	#[unsafe(no_mangle)]
	pub extern "C" fn frbgen_co_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCo(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Co>>::increment_strong_count(ptr as _);
	}

	#[unsafe(no_mangle)]
	pub extern "C" fn frbgen_co_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCo(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Co>>::decrement_strong_count(ptr as _);
	}

	#[unsafe(no_mangle)]
	pub extern "C" fn frbgen_co_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoContext(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoContext>>::increment_strong_count(ptr as _);
	}

	#[unsafe(no_mangle)]
	pub extern "C" fn frbgen_co_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoContext(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoContext>>::decrement_strong_count(ptr as _);
	}

	#[unsafe(no_mangle)]
	pub extern "C" fn frbgen_co_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoError(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoError>>::increment_strong_count(ptr as _);
	}

	#[unsafe(no_mangle)]
	pub extern "C" fn frbgen_co_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoError(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoError>>::decrement_strong_count(ptr as _);
	}

	#[unsafe(no_mangle)]
	pub extern "C" fn frbgen_co_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoPrivateIdentity(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoPrivateIdentity>>::increment_strong_count(
			ptr as _,
		);
	}

	#[unsafe(no_mangle)]
	pub extern "C" fn frbgen_co_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoPrivateIdentity(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoPrivateIdentity>>::decrement_strong_count(
			ptr as _,
		);
	}

	#[unsafe(no_mangle)]
	pub extern "C" fn frbgen_co_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoSubscription(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoSubscription>>::increment_strong_count(
			ptr as _,
		);
	}

	#[unsafe(no_mangle)]
	pub extern "C" fn frbgen_co_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoSubscription(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoSubscription>>::decrement_strong_count(
			ptr as _,
		);
	}
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
	// This file is automatically generated, so please do not edit it.
	// @generated by `flutter_rust_bridge`@ 2.11.1.

	// Section: imports

	use super::*;
	use crate::library::co::*;
	use crate::library::co_context::*;
	use crate::library::co_error::*;
	use crate::types::identity::*;
	use crate::types::storage::*;
	use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
	use flutter_rust_bridge::for_generated::wasm_bindgen;
	use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
	use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
	use flutter_rust_bridge::{Handler, IntoIntoDart};

	// Section: boilerplate

	flutter_rust_bridge::frb_generated_boilerplate_web!();

	#[wasm_bindgen]
	pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlockStorage(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BlockStorage>>::increment_strong_count(
			ptr as _,
		);
	}

	#[wasm_bindgen]
	pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlockStorage(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BlockStorage>>::decrement_strong_count(
			ptr as _,
		);
	}

	#[wasm_bindgen]
	pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCo(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Co>>::increment_strong_count(ptr as _);
	}

	#[wasm_bindgen]
	pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCo(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Co>>::decrement_strong_count(ptr as _);
	}

	#[wasm_bindgen]
	pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoContext(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoContext>>::increment_strong_count(ptr as _);
	}

	#[wasm_bindgen]
	pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoContext(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoContext>>::decrement_strong_count(ptr as _);
	}

	#[wasm_bindgen]
	pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoError(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoError>>::increment_strong_count(ptr as _);
	}

	#[wasm_bindgen]
	pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoError(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoError>>::decrement_strong_count(ptr as _);
	}

	#[wasm_bindgen]
	pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoPrivateIdentity(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoPrivateIdentity>>::increment_strong_count(
			ptr as _,
		);
	}

	#[wasm_bindgen]
	pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoPrivateIdentity(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoPrivateIdentity>>::decrement_strong_count(
			ptr as _,
		);
	}

	#[wasm_bindgen]
	pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoSubscription(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoSubscription>>::increment_strong_count(
			ptr as _,
		);
	}

	#[wasm_bindgen]
	pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoSubscription(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoSubscription>>::decrement_strong_count(
			ptr as _,
		);
	}
}
#[cfg(target_family = "wasm")]
pub use web::*;
